apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - billing.yaml
  - frontend.yaml
  - ingress-class.yaml
  - ingress-params.yaml
  - ingress.yaml
  - inventory.yaml
  - mysql.yaml
  - order.yaml
